name: delivery_project_app
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.0-406.0.dev <3.0.0'


dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  path_provider: ^2.0.14
  hydrated_bloc: ^9.1.0
  dio: ^5.1.1
  flutter_screenutil: ^5.7.0
  pin_code_fields: ^8.0.1
  lottie: ^2.3.2
  socket_io_client: ^2.0.1
  google_maps_flutter: ^2.2.5
#  flutter_polyline_points: ^1.0.0
#  location: ^4.4.0
  flutter_svg: ^2.0.5
  flutter_dotenv: ^5.0.2
  appcheck: ^1.0.6
  image_picker: ^1.0.6
  cached_network_image: ^3.2.3
  image_cropper: ^5.0.1
  get_ip_address: ^0.0.5
  geolocator: ^10.1.0
  android_intent_plus: ^4.0.1
  flutter_google_places_sdk: ^0.3.2+8
  geocoding: ^2.1.0
  fancy_shimmer_image: ^2.0.2
  shimmer: ^3.0.0
  #infinite_scroll_pagination: ^3.2.0
  palette_generator: ^0.3.3+2
  flutter_slidable: ^3.0.0
  fluttertoast: ^8.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  flutter_native_splash: ^2.3.1

flutter_native_splash:
  color: "#000000"
  image: assets/qc-logo.png
  android_12:
    image: assets/qc-logo.png
    color: "#000000"


flutter:

  uses-material-design: true

  assets:
    - .env
    - assets/
    - assets/images/


  fonts:
    - family: SF-Pro-Rounded
      fonts:
        - asset: assets/fonts/SF-Pro-Rounded-Regular.ttf